SELECT NUMERO, NOME FROM BANCO;

SELECT BANCO_NUMERO, NUMERO, NOME FROM AGENCIA;

SELECT NUMERO, NOME, EMAIL FROM CLIENTE;

SELECT BANCO_NUMERO, AGENCIA_NUMERO, NUMERO, DIGITO, CLIENTE_NUMERO FROM conta_corrente;

SELECT BANCO_NUMERO, AGENCIA_NUMERO, CLIENTE_NUMERO FROM cliente_transacoes;

SELECT ID, NOME FROM tipo_transacao;

SELECT BANCO_NUMERO, AGENCIA_NUMERO, CONTA_CORRENTE_NUMERO, CONTA_CORRENTE_DIGITO, CLIENTE_NUMERO, VALOR 
FROM cliente_transacoes;

SELECT COUNT(1) FROM BANCO; --151
SELECT COUNT(1) FROM AGENCIA; --296

SELECT BANCO.NUMERO, BANCO.NOME, AGENCIA.NUMERO, AGENCIA.NOME FROM BANCO
JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO

SELECT COUNT(BANCO.NUMERO) FROM BANCO --296
JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO

--CONTAGEM DO NÚMERO DE BANCOS SEM DUPLICIDADE
SELECT COUNT(DISTINCT BANCO.NUMERO) FROM BANCO --9 REGISTROS
JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO

--EXIBINDO OS DADOS AGRUPADOS
SELECT BANCO.NUMERO FROM BANCO --9 BANCOS
JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO
GROUP BY BANCO.NUMERO

SELECT BANCO.NUMERO, BANCO.NOME, AGENCIA.BANCO_NUMERO, AGENCIA.NOME 
FROM BANCO
LEFT JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO;

SELECT AGENCIA.NUMERO, AGENCIA.NOME, BANCO.NUMERO, BANCO.NOME 
FROM AGENCIA
RIGHT JOIN BANCO ON BANCO.NUMERO = AGENCIA.BANCO_NUMERO;

SELECT AGENCIA.NUMERO, AGENCIA.NOME, BANCO.NUMERO, BANCO.NOME 
FROM AGENCIA
LEFT JOIN BANCO ON BANCO.NUMERO = AGENCIA.BANCO_NUMERO;

SELECT BANCO.NUMERO, BANCO.NOME, AGENCIA.NUMERO, AGENCIA.NOME 
FROM BANCO
FULL JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO;

CREATE TABLE IF NOT EXISTS TESTE_A (ID SERIAL PRIMARY KEY, VALOR VARCHAR(10));
CREATE TABLE IF NOT EXISTS TESTE_B (ID SERIAL PRIMARY KEY, VALOR VARCHAR(10));
INSERT INTO TESTE_A (VALOR) VALUES('teste1');
INSERT INTO TESTE_A(VALOR) VALUES('teste2');
INSERT INTO TESTE_A(VALOR) VALUES('teste3');
INSERT INTO TESTE_A(VALOR) VALUES('teste4');

INSERT INTO TESTE_B (VALOR) VALUES('teste1');
INSERT INTO TESTE_B(VALOR) VALUES('teste2');
INSERT INTO TESTE_B(VALOR) VALUES('teste3');
INSERT INTO TESTE_B(VALOR) VALUES('teste4');

SELECT tabela_a.valor, tabela_b.valor from teste_a as tabela_a
cross join teste_b as tabela_b


select 	banco.nome, 
		agencia.nome, 
		conta_corrente.numero, 
		conta_corrente.digito, 
		cliente.nome
from banco
join agencia 
	on agencia.banco_numero = banco.numero
join conta_corrente 
	on conta_corrente.banco_numero  = banco.numero
	and conta_corrente.agencia_numero = agencia.numero
join cliente
	on cliente.numero = conta_corrente.cliente_numero;

