SELECT NUMERO, NOME FROM BANCO;

SELECT BANCO_NUMERO, NUMERO, NOME FROM AGENCIA;

SELECT NUMERO, NOME, EMAIL FROM CLIENTE;

SELECT BANCO_NUMERO, AGENCIA_NUMERO, NUMERO, DIGITO, CLIENTE_NUMERO FROM conta_corrente;

SELECT BANCO_NUMERO, AGENCIA_NUMERO, CLIENTE_NUMERO FROM cliente_transacoes;

SELECT ID, NOME FROM tipo_transacao;

SELECT BANCO_NUMERO, AGENCIA_NUMERO, CONTA_CORRENTE_NUMERO, CONTA_CORRENTE_DIGITO, CLIENTE_NUMERO, VALOR 
FROM cliente_transacoes;

SELECT COUNT(1) FROM BANCO; --151
SELECT COUNT(1) FROM AGENCIA; --296

SELECT BANCO.NUMERO, BANCO.NOME, AGENCIA.NUMERO, AGENCIA.NOME FROM BANCO
JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO

SELECT COUNT(BANCO.NUMERO) FROM BANCO --296
JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO

--CONTAGEM DO NÚMERO DE BANCOS SEM DUPLICIDADE
SELECT COUNT(DISTINCT BANCO.NUMERO) FROM BANCO --9 REGISTROS
JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO

--EXIBINDO OS DADOS AGRUPADOS
SELECT BANCO.NUMERO FROM BANCO --9 BANCOS
JOIN AGENCIA ON AGENCIA.BANCO_NUMERO = BANCO.NUMERO
GROUP BY BANCO.NUMERO